### PR TITLE
LPS-61134

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
Hey Zsigmond

I would like explain a bit about this fix.

Before, I (may be the CSE as well) believe the i18npath Liferay used in URL is something like, ``/en'', ''/hu''.

However, after having a look at getI18nPathLanguageId method in portalImpl.java
```
	public String getI18nPathLanguageId(
		Locale locale, String defaultI18nPathLanguageId) {

		String i18nPathLanguageId = defaultI18nPathLanguageId;

		if (!LanguageUtil.isDuplicateLanguageCode(locale.getLanguage())) {
			i18nPathLanguageId = locale.getLanguage();
		}
		else {
			Locale priorityLocale = LanguageUtil.getLocale(
				locale.getLanguage());

			if (locale.equals(priorityLocale)) {
				i18nPathLanguageId = locale.getLanguage();
			}
		}

		return i18nPathLanguageId;
	}
```

It seems that we use either languageId or languageCode as i18npath.

LanguageId means language with locale, i.e. "en_US', "pt_BR".

LanguageCode means language, i.e. "en", "pt"

``LanguageUtil.getLocale(i18nLanguageId)`` is getting locale from LanguageCode.

``LocaleUtil.fromLanguageId(i18nLanguageId)`` is getting locale from LanguageId.

I can see here the naming could be ambiguous as LanguageId could be language with locale, i.e."en_US', or the one directly from 18npath, which we do not know it is ''en_US'' or ''en", for example as we could use either.

The logic of getI18nPathLanguageId explain when we use language with locale(i.e. en_US) and when we use only language(en).

HTH
John.

**Comment by zsigmondrab** [comment]
I have just started to review this.

**Comment by zxdgoal** [comment]
https://github.com/zsigmondrab/liferay-portal/pull/132

**Pull request closed without merging**
