### PR TITLE
LPS-56711 Move the query logic from view_dynamic_list.jspf to public API

### PR DESCRIPTION
**Pull request by zsolah**
Hi,

Please review.

Thanks,
Zsolt

### CODE REVIEW

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
Hi,

I'm changing the SEARCH_WITH_INDEX boolean to be a parameter. Otherwise I think it is complete.

Zsolt

**Comment by zsolah** [comment]
ci:retest

**Comment by zsigmondrab** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/440

See my changes: https://github.com/zsigmondrab/liferay-portal/compare/c4793040306ba3fb51ebc6ae509238ef9c8aed1e...f50674ae5525617f5fbaf68ff2f3b098eb31c46d

Thank you,
Zsigmond

**Pull request closed without merging**
