### PR TITLE
[Technical-Support] LPS-66606 and LPS-66603

### PR DESCRIPTION
**Pull request by yuhai**
cc @daledotshan,

Hi Zsigmond,

Hope you are doing well.

I talk with dale. And I want to ask some help from you. I create one new class in portal-kernel, so our robot test script will exist LayoutStagedModelDataHandler java class can't be compiled successful. 

From my understanding, modules will get portal-kernel.jar from mavenLocal repositories. I can skip this error by pointing at specific jar in my side. However, for our robot test, it won't passed. I test the LPS-66606 fix in ee-6.2.x and it works for me. Due to ee-6.2.x and master has same logic, I directly submit the fix to master. Could you please help check how we deal with the issue? Because the fix is in export/import, could you please help review the fix? :)

**The fix explanation is as the following:**
Due to LPS-66606 uses new created LayoutRevisionThreadLocal class (in LPS-66603), this commit includes two different fix.

LPS-66603: When import two pages which exists portlets, we should re-setLayoutRevisionId so that import the second page can't affect the first imported page. Actually, LayoutRevisionThreadLocal came from the commit "LPS-22777 Can not save metadata in asset publisher configuration in staging", and this was SF/deleted(14245f9f9791cada394963dfa33fc86adcb011e8) to LayoutRevisionLocalServiceImpl class.

LPS-66606: When import layout to enabled layoutRevision staging site, we should create one new layoutrevision data instead of directly updating data in layout table. Because when edit one layout in staging site, it won't update layout table and it will create new layoutrevision data in layoutrevision table. Please refer to LPS-66606's description to know master and 6.2.x different behavior. On master, when import one blank page and this page will include some default portlets(for example, com_liferay_portal_search_web_portlet_SearchPortlet), so it won't have 6.2.x behavior. 

Best Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi Zsigmond,

Update build.gradle and packageinfo should pass build. However, after this, there are some osgi modules can't start. I am sorry I am not familiar with osgi framework. Will further check this.

Regards,
Hai

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi Zsigmond,

I just add commits and these can solve my previous encountered issue.

At here, I want to further explain the fix.

LPS-66603: When we add portlet one by one(or edit portletPreference) in one page, it also will separately add related data in layoutrevision table. So in the import progress, we also use the same logic with UI operation.

LPS-66606: This fix will definely fix the issue on ee-6.2.x. Because on ee-6.2.x, for one empty page, it doesn't include portlet in import lar. On master, we use the same logix in LayoutStagedModelDataHandler class. This won't add related data in layout table and it will create related data (*new page name*) in layoutrevision table. However, due to the empty layout includes some default portlets, so when update portletPreferences, it also will add new data in layoutrevision table. However, If the behavior is not right, from my viewpoint, this is new issue (I don't investigate the issue). We can fix the issue "export blank page which includes some default portlets" in  new LPS ticket.

Regards,
Hai

**Comment by zsigmondrab** [comment]
Just fetched :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zsigmondrab** [comment]
Hi Hai,

sorry but I will not have time for this today. Have you checked why there are still that much failed test?

Can you point any pattern to me that you followed at using a thread local class? Can you explain why we need that exactly?

Thank you for the help,
Zsigmond

**Comment by yuhai** [comment]
Hi Zsigmond,

For those failed test, I don't know the reason. On my side, all Modules can start successful. I will check this later.

Please also refers to my first commit explanation from https://github.com/zsigmondrab/liferay-portal/pull/140#issue-160371192


 >LPS-66603: When import two pages which exists portlets, we should re-setLayoutRevisionId so that  >import the second page can't affect the first imported page. Actually, LayoutRevisionThreadLocal  >came from the commit "LPS-22777 Can not save metadata in asset publisher configuration in  >staging", and this was SF/deleted(14245f9f9791cada394963dfa33fc86adcb011e8) to  >LayoutRevisionLocalServiceImpl class.

Please refer to the below explame:
Assumption: In lar, there are two layouts "page1" and "page2", in "page1", exist web content display portlet. In "page2", exist "asset publisher portlet". When import web content display, LayoutRevisionLocalServiceImpl will set "_layoutRevisionId.set(layoutRevision.getLayoutRevisionId());". *At this time, layoutRevision is "page1" related data. And then when import  "asset publisher portlet", due to we don't reset the value in _layoutRevisionId*, it will get "page1" layoutRevision data. At here, it should get "page2" layoutRevision data. So we need to reset the value so that when import more than one layout and this can works well.

Regards,
Hai

**Comment by yuhai** [comment]
ci:retest

**Comment by zsigmondrab** [comment]
Just fetched :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zsigmondrab** [comment]
Pull request submitted to https://github.com/giros/liferay-portal/pull/41. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi Zsigmond,

Thanks for reviewing the pull request. :)

I just want to update my findings regarding test failed. I submit one empty pull reuqest to test the robot test. It also exists simliar error. Please refer to https://github.com/daledotshan/liferay-portal/pull/432

Regards,
Hai

**Pull request closed without merging**
