### PR TITLE
LPS-53858 Apply to DL

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@zsigmondrab, could you please check that?

Thanks

**Comment by zsigmondrab** [comment]
Hi @marcellustavares,

I'll take an additional look at.

Thank you,
Zsigmond

**Comment by ssmith353** [comment]
Hey @zsigmondrab @marcellustavares,
I tested this, and it does show the correct structures, but with this implemented the user no longer has the ability to add any definitions for the non-staged portlet.

**Comment by zsigmondrab** [comment]
Hi @ssmith353, (@marcellustavares,)

thank you for catching that. I thought, I checked all of the possibilities, however, with this problem we bumped into a staging permission problem again. I'll get back soon.

Regards,
Zsigmond

**Comment by zsigmondrab** [comment]
Hi @marcellustavares, @ssmith353,

I've created a new pull request as it has a staging related modification also: https://github.com/matethurzo/liferay-portal/pull/946

I asked Máté to send the fix to you, Marcellus if that will pass by him.

Thank you,
Zsigmond

**Pull request closed without merging**
