### PR TITLE
LPS-61134 To field of Unit converter is not updated

### PR DESCRIPTION
**Pull request by zxdgoal**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey Zsigmond

The issue hidden in WSRP is that the page is redirect with i18npath "en_US".

It will the same if you test with url, i.e. http://localhost:8080/en_US.

**Comment by zsigmondrab** [comment]
Hi John,

unfortunately, the wsrp portlet did not work today so I could not test. I will take an additional look at on Monday.

In the meantime, what do you mean with "It will the same if you test with url, i.e. http://localhost:8080/en_US." exactly?

Did you want to write LPS-61135? I cannot see redirection loop problem at there.

Regards,
Zsigmond

**Comment by zxdgoal** [comment]
The root cause of  LPS-61134 is the same with inputting http://localhost:8080/en_US.

No need to use WSRP.

Just use http://localhost:8080/en_US for testing is enough.

They are the same issue.

Forget LPS-61135, 

It was my typo.

**Comment by zxdgoal** [comment]
Updated the test.

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zsigmondrab** [comment]
Forwarded to https://github.com/epgarcia/liferay-portal/pull/458

Thank you for your patience.

Zsigmond

**Pull request closed without merging**
