### PR TITLE
LPS-53858

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hi Zsigmond,

I'm sending this through you since you are the new global SME for Staging (among other things). I received this pull request from the US team but I do not have enough Staging knowledge to evaluate the fix's logic. I did some general source formatting, but was hoping you could take a look at the logic and let myself and @ssmith353 what you think about the fix.

Thanks!

### CODE REVIEW

**Comment by zsigmondrab** [comment]
I've just started to review. I will probably finish this tomorrow.

Thank you for your patience,
Zsigmond

**Comment by zsigmondrab** [comment]
Hi @jonathanmccann, @ssmith353,

are you completely sure about that the problem is that the Dynamic Data Mapping portlet gets staged?

As far as I can see, the real problem is that the groupId is wrong at structure listing in the /portal-web/docroot/html/portlet/dynamic_data_mapping/view.jsp. That is not using the scopeGroupId.

Actually, when an asset is not staged, all of the entries stay in the live group and the editing is going in the live group. As I can see, the real problem is that the structure listing is trying to get structures from the groupId variable, which is the staging group's id and not the live group's id (scopeGroupId) which should be used in case of the un-staged assets. That would be enough to use the scopeGroupId there also.

Am I missing something?

In addition, your change breaks an other modification which is connected to the publishing of the default values for a web content structure, as it seems, you didn't use the latest master branch. Is that possible? See https://github.com/brianchandotcom/liferay-portal/pull/24419/files

Let me know if I overlooked anything.

Thank you,
Zsigmond

**Comment by ssmith353** [comment]
Hey @zsigmondrab ,

I just tested this on 61e0705f59e08a1b3a4bc42e3718bc8a10139d75, which is directly after LPS-53343, I modified the DDM/view.jsp to reference the scopeGroupId - it returns the live site because it is fetching the groupId for the DDM portlet which is now staged not the scopeGroupId for the NON-staged DDL portlet.

I then hard coded the groupId from the staged site, and the Data Definitions do show up, but I do not have the option to add new data definitions becuase I am now referencing the groupId to the live site, within a staged portlet. (DDM).

rsz_2image

**Comment by zsigmondrab** [comment]
Hi @ssmith353,

I can take an additional look at tomorrow, however, till then, why do you think that ths DDM is staged? 

Actually, the DDM cannot be staged directly. The entries connected to the DDM will be staged if there is anything which is staged (DDL, WCM) to which they are connecting.

This is what is not clear to me and I need to do a double check, unless you can clarify completely.

Thank you,
Zsigmond

**Comment by zsigmondrab** [comment]
Hi @ssmith353,

ok, I can see now what you are referring to. The problem is that, all of the portlets with *PortletDataHandler class will be staged unless you cannot set that to be not staged through the UI. It's designed in this way, so it would be pretty hard to change that. As there is not such an entry on the UI, the DDMStructure portlet will be staged all the times.

I think, this is the main problem, as you pointed out also.

However, the DDMStructure portlet should never be staged as the entries there are staged only if the model to which they are connected is staged (JournalArticle, DDL). So the entries are and not the portlet is staged.

That is what we should try to fix first. I'm on that and will get back soon.

Thank you for your patience,
Zsigmond

**Comment by ssmith353** [comment]
Hey @zsigmondrab,

Thanks for taking the time to look at this; it's somewhat complicated to explain but I'm glad you were able to figure it out!

Let me know if there's anything I can do to help!

-Steven

**Comment by zsigmondrab** [comment]
Hi @jonathanmccann, @ssmith353,

I sent a solution to @marcellustavares which I created in the light of that I've written here before in my previous comments. See https://github.com/marcellustavares/liferay-portal/pull/431

The fix: https://github.com/zsigmondrab/liferay-portal/commit/23b8399da77525374d757b1c341d35bc9a3cbc8a

Regards,
Zsigmond

**Pull request closed without merging**
