### PR TITLE
[Technical Support] LPS-60636 Redirection does not happen for locals which are not in locales.enabled

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Zsigmond

This works in Trunk but not in branch 6.2.

The issue for 6.2. is that in PortletBagFactory.java
```
			if (supportedLanguageIds.isEmpty()) {
				supportedLanguageIds = SetUtil.fromArray(PropsValues.LOCALES);
			}

			for (String supportedLanguageId : supportedLanguageIds) {
				Locale locale = LocaleUtil.fromLanguageId(supportedLanguageId);

				initResourceBundle(resourceBundles, portlet, locale);
			}
```

These code add all locales in "'locales" in portal.properties into LocaleUtil.

So ``loacles.enabled`` does not even work for LocaleUtil.

These code are simply removed by Ray in Trunk

But I do not think it is safe to remove them in branch 6.2 as PortletBagFactory.java has been changed to get adapted to OSGI in Turnk

Back to the issue.

Is it safe to change ``PropsValues.LOCALES`` to ``PropsValues.LOCALES_ENABLE`` for 6.2?

What the main difference between these two properties according their definitions?

Anyway, the fix for trunk is free to go.

Thanks
John

### CODE REVIEW

**Comment by zsigmondrab** [comment]
Hi @juliocamarero,

could you please take a look at John's comment.

As for fixing this on master, we have a new problem that we did not consider lat time, namely, if the enabled locales has been changed in the properties file the redirection fails.

This new fix changes the behaviour as if a language is not enabled, the url will be a missing resource. I think, from the search robots perspective, this is a more reasonable working than do a fallback to the default language, as at the second case, there is still the same content between two urls.

As for fixing this on 6.2, I will take a look at that also, but in the meantime, do you think removing that code can be a problem?

@zxdgoal, please let me know if I misunderstand anything.

Thank you in advance,
Zsigmond

**Comment by zsigmondrab** [comment]
Hi @zxdgoal,

should we not apply the same change within the setAlternativeLayoutFriendlyURL() method here: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/FriendlyURLServlet.java#L418-L419?

Regards,
Zsigmond

**Comment by zxdgoal** [comment]
No, the locale in setAlternativeLayoutFriendlyURL will be returned.

That is it could be used by other methods.

Across the portal, we do not accept null as a legal locale and it could cause NPE as well.

The i18nLocale in https://github.com/zxdgoal/liferay-portal/blob/44ac7f239a8a642bfd5c9bf0e9d9da3afd3b7657/portal-impl/src/com/liferay/portal/servlet/FriendlyURLServlet.java#L355 is different.

It is just for checking and will be destroyed after checking.

So we accept null as i18nLocale in this case

Thanks
John.

**Comment by zxdgoal** [comment]
@ealonso Could you help us on this issue?

Thanks
John.

**Comment by epgarcia** [comment]
Hi @zxdgoal,

The LOCALES_ENABLE property contains only the locales enabled by default, as a subset of the LOCALES. But the enabled locales can be modified from those default values for every portal instance through the UI (Portal Configuration -> Display Settings). In other words, you shouldn't perform any action based on the LOCALES_ENABLE property, except loading the portal instance default enabled locales the first time (See [LanguageImpl](https://github.com/liferay/liferay-portal/blob/1c9fd4fc9edd3791838c62169372d019ce566fbc/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L1039)). 

Could not we simply redirect to default if LanguageUtil.isAvailableLocale(group, urlLocale) is false?

Thanks!

**Comment by zxdgoal** [comment]
Hey @epgarcia 

Thanks for your explanation.
> Could not we simply redirect to default if LanguageUtil.isAvailableLocale(group, urlLocale) is false?

Did you mean the code here: https://github.com/zxdgoal/liferay-portal/blob/44ac7f239a8a642bfd5c9bf0e9d9da3afd3b7657/portal-impl/src/com/liferay/portal/servlet/FriendlyURLServlet.java#L358-L361

When LanguageUtil.isAvailableLocale return false, we expect a redirection to original locale.

The problem is if a locale say, fr is not in ``LOCALES_ENABLE``.

The LocaleUtil.fromLanguageId('fr') will return default locale ``en_us``.

But we expect null as the result as French is not an enable locale.

So ``LanguageUtil.isAvailableLocale(group, null)`` could return false then a redirection happens.

The fix works in Trunk. But more work is required for 6.2.X for this issue.

Thanks
John.

**Comment by zsigmondrab** [comment]
Forwarded to https://github.com/eduardolundgren/liferay-portal/pull/505

Thank you,
Zsigmond

**Pull request closed without merging**
