### PR TITLE
LPS-59252 Use layout's friendly URL if we cannot fetch it from the request URL, so that we can move on to decide whether a redirection should occur for urls which do not include layout friendly URLs explicitly, i.e. localhost:8080/fr/ .

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @zsigmondrab 

can you help me with this pull? This is a very sensitive point and I am not sure this is the best solution...

thanks a lot!

### CODE REVIEW

**Comment by zxdgoal** [comment]
Fix with test here: https://github.com/hhuijser/liferay-portal/pull/2519

**Comment by zsigmondrab** [comment]
Hi @zxdgoal,

basically, it seems to work all the cases we had till now, however, as I can see when we use virtual host for a layout set, so there should not be the /web/group-friendly-url in the url, when I am using an unknown language, like fr in our case, the http://somehost.com/fr will change to http://somehost.com/en/web/group-friendly-url instead of http://somehost.com/en.

However, I did not have time to check if this is because of this fix or this was only a hidden bug that could not be experienced before.

Could you please take a look at if you experience the same?

Thank you,
Zsigmond

**Comment by zxdgoal** [comment]
Hey Zsigmond

This is a hidden issue.

Following steps below, the issue can be reproduced without my fix involved.

Add a page with English URL as /ee and Hungarian URL as /hh

somehost.com as public page URL.

Input somehost.com/en/hh.

You are expected to redirected to somehost.com/en/ee.

But it is somehost.com/en/web/guest/ee.

I think this is a good catch. we need fix this anyway.

Thanks
John.

**Comment by zxdgoal** [comment]
A new fix here: https://github.com/hhuijser/liferay-portal/pull/2521.

**Comment by zsigmondrab** [comment]
I'll continue the review here: https://github.com/zsigmondrab/liferay-portal/pull/120

Thank you,
Zsigmond

**Pull request closed without merging**
