### PR TITLE
LPS-54172

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey Zsigmond,

I saw that you were involved in deeming this behavior a bug so I was wondering if you wouldn't mind taking a look at the fix for it. I'm not well versed in staging so I'm not sure if this is an appropriate solution or not. Please let me know if you have any questions. Thanks!

/cc @ssmith353 @bryanengler

### CODE REVIEW

**Comment by zsigmondrab** [comment]
Hi @jonathanmccann, @ssmith353,

I have one question. Your solution is working, however, is there any reason why you don't follow the pattern implemented in case of web contents?

The ExportImportHelperUtil.replaceExportContentReferences() method is being called from the JournalArticleStagedModelDataHandler.doExportStagedModel() method there and that one seemingly handles all of the references automatically.

Thank you,
Zsigmond

**Comment by ssmith353** [comment]
Hey @zsigmondrab, within JASMDH, we actually store all referenced content within a JournalArticle with a CDATA tag, so it is very easy to parse, and determine that references exist. 

In the case of JournalArticle, it follows this pattern when exported. 
contentforJournalArticle[CDATA[imageReference]],moreJournalContent. 

In the case of we can easily find and replace the content references. 

Whereas in the case of DDL, everything is contained within fields, and is not easily identifiable as a content reference. The content is individually contained within each field, and looks like: 

{"groupId":"20181","title":"someFile.zip","uuid":"c88fcd97-7ad3-c192-6933-5676be3e0301"}

Which does not follow the same pattern for replaceExportContentReferences, so they must be individually parsed base on their "type."

**Comment by zsigmondrab** [comment]
Hi @ssmith353,

basically, the code looks fine. I would do only one source format at the order of the PortletDataHandlerBoolean objects in the DDLPortletDataHandler class with putting the "referenced-content" one at the end of the list.

Besides, I've found one problem. The groupIds aren't changed in the data_ column of the appropriate DDMContent table entries. The imported entries has the groupId of the original site.

Could you please take a look at that?

Regards,
Zsigmond

**Comment by ssmith353** [comment]
Hey @zsigmondrab,
I'll make the SF in DDLPDH - as for the DDMContent I think it will only be changing the import of the "groupId" in the JsonObject - I'm testing this now. 

Thanks!
-Steven

**Comment by ssmith353** [comment]
Hey @zsigmondrab, 
Changing the groupId from using the imported value to the PDC.getGroupid() uses the correct groupId from the current site. Would you like me to send you an updated pull directly? 

Thanks!

**Comment by zsigmondrab** [comment]
I'm closing this one as a new one has been sent: https://github.com/zsigmondrab/liferay-portal/pull/99

Thank you for the corrections.

Zsigmond

**Pull request closed without merging**
