### PR TITLE
LPS-55201 Indexing fails for repeteable Date fields with blank values

### PR DESCRIPTION
**Pull request by sergiosanchez**

### CODE REVIEW

**Comment by sergiosanchez** [comment]
Hey @zsigmondrab 
I guess this PR is for you, as WEM SME.
Could you review it?

Thanks

**Comment by zsigmondrab** [comment]
I've just started to review.

Regards,
Zsigmond

**Comment by zsigmondrab** [comment]
I takes a bit longer as the web content management is not working on the current master to me.

Zsigmond

**Comment by zsigmondrab** [comment]
I've asked Marcellus to take a look at our solutions: https://github.com/marcellustavares/liferay-portal/pull/470

Regards,
Zsigmond

**Comment by zsigmondrab** [comment]
I'm closing this pull request for now. The solution was good, however, @marcellustavares would like to take more time to rewrite how we're indexing DDM contents on the portal.

Thank you,
Zsigmond

**Pull request closed without merging**
