### PR TITLE
Lps 66500

### PR DESCRIPTION
**Pull request by dsanz**

### CODE REVIEW

**Comment by dsanz** [comment]
ci:retest

**Comment by dsanz** [comment]
Hi Zsigmond,

I think I forgot to update some stuff about module versions, let me take a
look to it

Best

On Fri, Jun 10, 2016 at 11:47 AM, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 1 hour 8 minutes 23 seconds
> Base Branch:
>
> Branch Name: master
> <https://github.com/liferay/liferay-portal/tree/master>
> Branch GIT ID: a2ca9eda4c8d83dcc75e06167b2be14966fcf878
> <https://github.com/liferay/liferay-portal/commit/a2ca9eda4c8d83dcc75e06167b2be14966fcf878>
> Job Summary:
>
>    - *test-portal-acceptance-pullrequest(master)
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/225/>*
>    - test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk7
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11588/>
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-jboss64-mysql56-jdk8/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11589/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-hypersonic20-jdk7/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11590/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11592/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/1
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11591/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/2
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11593/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11594/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/1
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11595/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/10
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12162/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/11
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10300/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/12
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11600/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/13
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11599/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/14
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11598/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/15
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11601/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/16
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11604/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/17
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11603/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/18
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11602/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/19
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11605/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/2
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11597/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/20
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11611/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/21
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11610/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/22
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11609/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/23
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11608/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/24
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11706/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/25
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11607/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/26
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11606/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/27
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11615/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/28
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11614/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/29
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11613/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/3
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11596/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/30
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11612/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/31
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11616/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/32
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11617/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/33
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12163/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/34
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11345/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/35
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10732/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/36
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10731/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/37
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10730/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/38
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10729/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/39
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10728/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/4
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12161/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/40
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10727/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/41
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10726/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/42
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10725/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/43
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10724/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/44
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10723/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/45
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10722/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/5
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12160/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/6
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12159/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/7
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12158/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/8
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12157/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/9
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12156/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-oracle12-jdk8/0
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10735/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-oracle12-jdk8/1
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10734/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-oracle12-jdk8/2
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11707/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/0
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11708/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/1
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11709/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/2
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11250/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/0
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11251/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/1
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11892/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-sybase16-jdk8/2
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11891/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-weblogic121-mysql56-jdk8/0
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10782/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-wildfly10-mariadb100-jdk8/0
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10783/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-db2105-jdk7
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11252/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-hypersonic20-jdk7
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11253/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-mysql56-jdk7
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12106/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-oracle12-jdk7
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12107/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-postgresql94-jdk7
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11710/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-sybase160-jdk7
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11893/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/lpkg-startup-jdk7
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10785/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-db2105-jdk7
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10301/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic20-jdk7
>    <https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10469/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql56-jdk7
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10164/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-oracle12-jdk7
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11657/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql94-jdk7
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10784/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-sybase160-jdk7
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11254/>*
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk7
>    <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11053/>*
>    - test-portal-acceptance-pullrequest-batch(master)/plugins-compile-jdk7
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/12108/>
>    - test-portal-acceptance-pullrequest-batch(master)/portal-web-jdk7
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9434/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/ruby-sass-compiler-jdk7
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11346/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk7
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11894/>
>    - test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk7
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11711/>
>    - *test-portal-acceptance-pullrequest-batch(master)/tck-jdk7
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11895/>*
>    - test-portal-acceptance-pullrequest-batch(master)/unit-jdk7
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10736/>
>    - test-portal-acceptance-pullrequest-source(master)
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/210/>
>
> For more details click here
> <https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/225/jenkins-report.html>
> .
> ------------------------------
> Failed Jobs:
>
>    1. test-portal-acceptance-pullrequest(master)
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/225/> Job
>    Results:
>
>    8 Jobs Passed.
>    78 Jobs Failed.
>
>    Completed with the status of FAILURE.
>
>    2.
>    test-portal-acceptance-pullrequest-batch(master)/functional-jboss64-mysql56-jdk8/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11589/> Job
>    Results:
>
>    0 Tests Passed.
>    1 Test Failed.
>    1. *test-portal-acceptance-pullrequest-batch(master) ?? 0,!master
>       #11589
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/11589/>*
>
>            [exec] �[0m�[31m09:07:00,365 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS013413: Timeout after [5000] seconds waiting for service container stability while finalizing an operation. Process must be restarted. Step that first updated the service container was 'add' at address '[
>
>            [exec]     ("core-service" => "management"),
>
>            [exec]     ("management-interface" => "native-interface")
>
>            [exec] ]'
>
>            [exec] �[0m�[31m09:07:00,367 FATAL [org.jboss.as.server] (Controller Boot Thread) JBAS015957: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
>
>          [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:582: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-jboss.xml:30: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-jboss.xml:7: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8213: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2815: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2907: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3325: No server is available at http://localhost:8080/web/guest
>
>             [get] Getting: http://test-1-2/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/11589//consoleText
>
>             [get] To: /opt/dev/projects/github/liferay-portal/20160610021313619.txt
>
>          [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160610021313619.txt
>
>       3.
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-hypersonic20-jdk7/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11590/> Job
>    Results:
>
>    0 Tests Passed.
>    1 Test Failed.
>    1. *test-portal-acceptance-pullrequest-batch(master) ?? 0,!master
>       #11590
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/11590/>*
>
>            [exec]    at org.eclipse.osgi.container.Module.start(Module.java:429)
>
>            [exec]   at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
>
>            [exec]   at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
>
>            [exec]   at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
>
>            [exec]   at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
>
>            [exec]   at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
>
>            [exec]   at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:582: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:48: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:56: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8213: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2815: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2910:
>
>            [echo] exec returned: 1
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3255: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3419: Unable to find startup message after 15 minutes.
>
>             [get] Getting: http://test-1-2/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/11590//consoleText
>
>             [get] To: /opt/dev/projects/github/liferay-portal/20160610021318138.txt
>
>          [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160610021318138.txt
>
>       4.
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11592/> Job
>    Results:
>
>    0 Tests Passed.
>    1 Test Failed.
>    1. *test-portal-acceptance-pullrequest-batch(master) ?? 0,!master
>       #11592
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/11592/>*
>
>            [exec]
>
>            [exec]   at org.eclipse.osgi.container.Module.start(Module.java:429)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
>
>            [exec]   at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
>
>            [exec]   at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:582: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:48: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:56: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8213: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2815: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2910:
>
>            [echo] exec returned: 1
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3255: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3419: Unable to find startup message after 15 minutes.
>
>             [get] Getting: http://test-1-2/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/11592//consoleText
>
>             [get] To: /opt/dev/projects/github/liferay-portal/20160610021459637.txt
>
>          [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160610021459637.txt
>
>       5.
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mariadb100-jdk8/1
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11591/> Job
>    Results:
>
>    0 Tests Passed.
>    1 Test Failed.
>    1. *test-portal-acceptance-pullrequest-batch(master) ?? 0,!master
>       #11591
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/11591/>*
>
>            [exec]
>
>            [exec]   at org.eclipse.osgi.container.Module.start(Module.java:429)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
>
>            [exec]   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
>
>            [exec]   at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
>
>            [exec]   at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:582: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:48: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:56: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8213: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2815: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2910:
>
>            [echo] exec returned: 1
>
>            [echo] The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3255: The following error occurred while executing this line:
>
>            [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3419: Unable to find startup message after 15 minutes.
>
>             [get] Getting: http://test-1-2/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/11591//consoleText
>
>             [get] To: /opt/dev/projects/github/liferay-portal/20160610021107040.txt
>
>          [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160610021107040.txt
>
>       6. ...
>
> For upstream results, click here
> <http://test-1-1/job/test-portal-acceptance-upstream(master)/>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zsigmondrab/liferay-portal/pull/139#issuecomment-225140785>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA0jVvdmY60IwM1f8Hf48RRDAPj3VRa8ks5qKTKegaJpZM4IyBmA>
> .
>



-- 

Daniel Sanz

Senior Software Engineer, Technical Support

Subscription Services | Spain and Portugal

Liferay Spain and Portugal
Tel. +34 91 733 63 43
<http://liferay.com/>
Enterprise. Open Source. For Life
Síguenos en  <http://www.facebook.com/pages/Liferay/45119213107>
<http://www.facebook.com/pages/Liferay/45119213107>
<https://twitter.com/liferay_es>  <http://www.liferay.com/about-us/news>

Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es


*AVISO DE CONFIDENCIALIDAD: **“La información contenida en este mensaje y/o
archivo(s) adjunto(s), enviados desde LIFERAY SL, es
confidencial/privilegiada y está destinada a ser leída sólo por la(s)
persona(s) a la(s) que va dirigida. **Si usted lee este mensaje y no es el
destinatario señalado, o ha recibido esta comunicación por error, le
informamos que está totalmente prohibida, y puede ser ilegal, cualquier
divulgación, distribución o reproducción de esta comunicación, y le rogamos
que nos lo notifique inmediatamente y nos devuelva el mensaje original a la
dirección arriba mencionada. **Gracias.”*

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by zsigmondrab** [comment]
Hi Daniel,

have you managed to check what you wanted to check?

Regards,
Zsigmond

**Comment by dsanz** [comment]
still working on this. Not sure why but there is a broken dependency.

**Comment by dsanz** [comment]
Ahhhhhhh got it, it's about the modules/core/portal-bootstrap/system.packages.extra.mf contents. Will send tomorrow

**Comment by zsigmondrab** [comment]
Should I close this one or you will refresh?

**Comment by dsanz** [comment]
Sorry Zsigmond, I could not make any progresss. Let me close it and resend rebased and with the proper files to respect Semver.

Best

**Pull request closed without merging**
