### PR TITLE
LPS-53554 URLs in sitemap.xml are repeated for web content

### PR DESCRIPTION
**Pull request by zsolah**
Hello,

This time I'm using the same solution which I used in the hotfix.

Please review.

Thanks.

### CODE REVIEW

**Comment by zsigmondrab** [comment]
As we talked, I think, the query which is used in the Journal portlet's view.jsp could be used to get the latest articles.

Could you please take a look at that?

Thank you,
Zsigmond

**Comment by juliocamarero** [comment]
Hey @zsigmondrab,

we are reviewing the bugs in our dashboards and we reached this one. Is @zsolah going to work in the change you asked him? 

Otherwise, could you explain us the changes you wanted him to do so that we can close this ticket? thanks!

**Comment by zsolah** [comment]
Hi,

The code has been moved to JournalArticleSiteMapURLProvider, I tried to reproduce on current master but at the Site settings the search engine optimization part is missing. I was unable to generate a sitemap.

**Comment by zsolah** [comment]
Hi,

To answer your question I'm going to work on this. Is it urgent? Do you know if the removal of Search engine optimization section is intended?

Regards,
Zsolt

**Comment by jkappler** [comment]
Hi @zsolah, you can find it now in Pages > Site Pages, it's not in Site Settings anymore

**Comment by zsolah** [comment]
Thanks @jkappler

**Comment by juliocamarero** [comment]
Hey @zsolah 

it is not extremely urgent, but we would appreciate if this can be fixed before the end of next week so that we can include this fix in next release.

thanks

**Pull request closed without merging**
