### PR TITLE
LPS-102310 Take the latest uuid, when uploading an image in iOS the name of the image is a valid UUID triggering the regex

### PR DESCRIPTION
**Pull request by victorg1991**
The problem is that when you upload an image in iOS from the mobile library, the file name is set to a valid UUID, and in the 

DLReferencesExportImportContentProcessor class, when trying to get the uuid from the url, it takes the name of the file as the uuid, resulting in this error

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by zsigmondrab** [comment]
@victorg1991, have you forwarded this already to @moltam89?

**Comment by moltam89** [comment]
Yes, it's merged: https://github.com/brianchandotcom/liferay-portal/pull/79113

**Comment by zsigmondrab** [comment]
Thanks

**Pull request closed without merging**
